# Generated by Django 3.1.6 on 2021-04-27 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthcare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=20)),
                ('Dentist', models.BooleanField(default=False)),
                ('Opthalmologist', models.BooleanField(default=False)),
                ('Orthopaedic', models.BooleanField(default=False)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('total', models.BooleanField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'health',
            },
        ),
        migrations.DeleteModel(
            name='Donors',
        ),
    ]
